language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
env:
  - ANTELOPE_CATALOG_ROOT="./CATALOG_ROOT"
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pip install -U importlib_metadata ; fi
install:
  - pip install coverage coveralls
  - pip install --no-deps -r requirements.txt
script:
  - coverage run --source=antelope_foreground -m unittest
after_success:
  coveralls
